name: Deploy to Firebase

on:
  push:
    branches:
      - main               # Deploys on push to the main branch
      - working_branch      # Deploys on push to the working branch
  pull_request:
    types: [closed]
    branches:
      - main               # Deploys on pull requests targeting the main branch if merged

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Ensure you've added this in GitHub Secrets
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/working_branch" ]]; then
            firebase hosting:channel:deploy staging-server
            firebase hosting:channel:list
          else
            firebase deploy
          fi
